-- supabase/migrations/001_initial.sql
-- SellMyiPhone initial schema, RLS policies, and triggers.
-- Run this against a fresh Supabase Postgres database.
-- NOTE: once applied to a real database, do NOT edit this file. Add a new
-- migration file (002_*.sql, ...) for any further structural changes.

-- ──────────────────────────────────────────────────────────────────────────
-- Tables
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text,
  phone       text unique,
  email       text,
  role        text not null default 'customer' check (role in ('customer','admin')),
  created_at  timestamptz default now()
);

create table if not exists public.models (
  id          uuid primary key default gen_random_uuid(),
  slug        text unique not null,
  name        text not null,
  category    text not null default 'iphone' check (category in ('iphone','macbook')),
  series      text not null,
  variants    jsonb,
  chips       jsonb,
  rams        jsonb,
  storages    jsonb not null,
  is_active   boolean default true,
  sort_order  int default 0,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create table if not exists public.questions (
  id              uuid primary key default gen_random_uuid(),
  order_index     int not null,
  category        text not null default 'iphone' check (category in ('iphone','macbook','all')),
  type            text not null check (type in ('single','multi','matrix')),
  question_text   text not null,
  hint_text       text,
  exclusive_option text,
  options         jsonb,
  matrix_items    jsonb,
  is_active       boolean default true,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

create table if not exists public.enquiries (
  id            uuid primary key default gen_random_uuid(),
  display_id    text unique not null,
  user_id       uuid references public.profiles(id),
  devices       jsonb not null,
  total_amount  int not null,
  address       text not null,
  pincode       text not null,
  pickup_slot   text not null,
  payment_mode  text not null check (payment_mode in ('UPI','Cash')),
  status        text not null default 'pending'
                check (status in ('pending','accepted','completed','rejected','cancelled')),
  tracking_step int not null default 0 check (tracking_step between 0 and 4),
  assigned_exec text,
  internal_note text,
  rating        int check (rating between 1 and 5),
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

create table if not exists public.enquiry_history (
  id          uuid primary key default gen_random_uuid(),
  enquiry_id  uuid references public.enquiries(id) on delete cascade,
  actor       text not null check (actor in ('customer','admin')),
  action      text not null,
  created_at  timestamptz default now()
);

create table if not exists public.enquiry_photos (
  id            uuid primary key default gen_random_uuid(),
  enquiry_id    uuid references public.enquiries(id) on delete cascade,
  slot          text not null check (slot in ('front','back','settings','left','right')),
  storage_path  text not null,
  created_at    timestamptz default now()
);

create table if not exists public.reviews (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  city          text not null,
  rating        int not null check (rating between 1 and 5),
  review_text   text not null,
  is_published  boolean default true
);

-- ──────────────────────────────────────────────────────────────────────────
-- Triggers / functions
-- ──────────────────────────────────────────────────────────────────────────

-- Human-friendly enquiry id, e.g. ENQ73210
create or replace function public.generate_display_id() returns trigger as $$
begin
  if new.display_id is null or new.display_id = '' then
    new.display_id := 'ENQ' || floor(random() * 90000 + 10000)::text;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_display_id on public.enquiries;
create trigger set_display_id
  before insert on public.enquiries
  for each row execute function public.generate_display_id();

-- updated_at maintenance
create or replace function public.touch_updated_at() returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists touch_models on public.models;
create trigger touch_models before update on public.models
  for each row execute function public.touch_updated_at();

drop trigger if exists touch_questions on public.questions;
create trigger touch_questions before update on public.questions
  for each row execute function public.touch_updated_at();

drop trigger if exists touch_enquiries on public.enquiries;
create trigger touch_enquiries before update on public.enquiries
  for each row execute function public.touch_updated_at();

-- Create a profiles row on signup. Handles email/password, Google OAuth and phone OTP.
-- phone or email may be null depending on provider.
create or replace function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, full_name, phone, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.phone,
    new.email,
    'customer'
  )
  on conflict (id) do nothing;
  -- TODO: account linking by phone/email match (merge Google sign-in with an
  -- existing phone-based profile) — deferred to v1.1.
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ──────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- ──────────────────────────────────────────────────────────────────────────

-- Helper: is the current user an admin?
create or replace function public.is_admin() returns boolean as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$ language sql security definer stable;

-- profiles
alter table public.profiles enable row level security;
create policy "profiles self read"   on public.profiles for select using (auth.uid() = id or public.is_admin());
create policy "profiles self update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "profiles self insert" on public.profiles for insert with check (auth.uid() = id);

-- enquiries
alter table public.enquiries enable row level security;
create policy "enquiries owner select" on public.enquiries for select using (user_id = auth.uid() or public.is_admin());
create policy "enquiries owner insert" on public.enquiries for insert with check (user_id = auth.uid());
create policy "enquiries owner update" on public.enquiries for update using (user_id = auth.uid() or public.is_admin());
create policy "enquiries admin delete" on public.enquiries for delete using (public.is_admin());

-- enquiry_history (join to enquiry user_id)
alter table public.enquiry_history enable row level security;
create policy "history read" on public.enquiry_history for select using (
  exists (select 1 from public.enquiries e where e.id = enquiry_id and (e.user_id = auth.uid() or public.is_admin()))
);
create policy "history insert" on public.enquiry_history for insert with check (
  exists (select 1 from public.enquiries e where e.id = enquiry_id and (e.user_id = auth.uid() or public.is_admin()))
);

-- enquiry_photos (join to enquiry user_id)
alter table public.enquiry_photos enable row level security;
create policy "photos read" on public.enquiry_photos for select using (
  exists (select 1 from public.enquiries e where e.id = enquiry_id and (e.user_id = auth.uid() or public.is_admin()))
);
create policy "photos insert" on public.enquiry_photos for insert with check (
  exists (select 1 from public.enquiries e where e.id = enquiry_id and (e.user_id = auth.uid() or public.is_admin()))
);

-- models: public read, admin write
alter table public.models enable row level security;
create policy "models public read" on public.models for select using (true);
create policy "models admin write"  on public.models for all using (public.is_admin()) with check (public.is_admin());

-- questions: public read, admin write
alter table public.questions enable row level security;
create policy "questions public read" on public.questions for select using (true);
create policy "questions admin write"  on public.questions for all using (public.is_admin()) with check (public.is_admin());

-- reviews: public read of published, admin write
alter table public.reviews enable row level security;
create policy "reviews public read" on public.reviews for select using (is_published or public.is_admin());
create policy "reviews admin write"  on public.reviews for all using (public.is_admin()) with check (public.is_admin());

-- ──────────────────────────────────────────────────────────────────────────
-- Storage bucket for enquiry photos
-- ──────────────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('enquiry-photos', 'enquiry-photos', false)
on conflict (id) do nothing;

create policy "photo upload own folder" on storage.objects for insert to authenticated
  with check (bucket_id = 'enquiry-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "photo read own or admin" on storage.objects for select to authenticated
  using (bucket_id = 'enquiry-photos' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()));

-- Helpful indexes
create index if not exists idx_enquiries_user on public.enquiries(user_id);
create index if not exists idx_enquiries_status on public.enquiries(status);
create index if not exists idx_models_category on public.models(category);
create index if not exists idx_questions_category on public.questions(category, order_index);
